name: bima_finance
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  path_provider: ^2.0.2
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.0
  photo_view: ^0.13.0
  image: ^3.0.2
  webview_flutter: ^2.0.8
  get_it: ^7.1.3
  font_awesome_flutter: ^9.0.0
  skeleton_text: ^3.0.0
  badges: ^2.0.1
  flutter_swiper: ^1.1.6
  toast: ^0.1.5
  carousel_slider: ^3.0.0
  google_fonts: ^2.1.0
  google_ml_kit: ^0.6.0
  # camera: ^0.8.1+3
  camera: ^0.9.4+8
  flutter_native_image: ^0.0.6
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  status_change: ^2.0.0
  url_launcher: ^6.0.17
  flutter_map: ^0.14.0
  location: ^4.1.1
  html: ^0.15.0
  flutter_html: ^2.2.1
  flutter_masked_text: ^0.8.0
  introduction_screen: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  package_info_plus: ^1.3.0
  flutter_inappwebview: ^5.3.2
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/wilayah.json
  fonts:
    - family: Maison-Neue
      fonts:
        - asset: assets/fonts/Maison-Neue.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_circle.png"